import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Download, FileJson, Printer, Share2 } from 'lucide-react';
import { usePageChrome } from '@/layouts/AppLayout';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/context/ToastContext';
import { useDatabase } from '@/hooks/useDatabase';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { StatusBadge, SeverityBadge } from '@/components/ui/Badge';
import {
  REPORT_DISCLAIMER,
  buildReportHtml,
  downloadEditableReport,
  downloadReportJson,
  getReport,
  printReport,
  setReportStatus,
} from '@/services/reportService';
import { getInspection, listEvidence } from '@/services/inspectionService';
import { resolveImage } from '@/services/imageService';
import { formatDateTime, RULE_STATUS_LABEL, STATUS_LABEL } from '@shared/lib/format';
import { cn } from '@/lib/utils';

export default function ReportDetail() {
  const { id = '' } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const toast = useToast();

  const report = useDatabase(() => getReport(id), [id]);
  const inspection = useDatabase(() => (report ? getInspection(report.inspectionId) : undefined), [id, report?.inspectionId]);
  const evidence = useDatabase(() => (report ? listEvidence(report.inspectionId) : []), [id, report?.inspectionId]);

  const html = inspection && user ? buildReportHtml(inspection, user, id) : '';

  usePageChrome(
    {
      title: report ? `Report ${report.id}` : 'Report',
      subtitle: report ? `${report.productName} · generated by ${report.generatedBy}` : undefined,
      actions: report ? (
        <div className="flex items-center gap-2">
          <Button size="sm" variant="outline" icon={<Printer size={13} />} onClick={() => printReport(html)}>
            <span className="hidden sm:inline">Print / PDF</span>
          </Button>
          <Button
            size="sm"
            icon={<Download size={13} />}
            onClick={() => {
              downloadEditableReport(html, report.id);
              toast.success('Editable report exported', `${report.id}.doc downloaded.`);
            }}
          >
            <span className="hidden sm:inline">Export editable</span>
            <span className="sm:hidden">Export</span>
          </Button>
        </div>
      ) : undefined,
    },
    [report?.id, html],
  );

  if (!report || !inspection) {
    return (
      <EmptyState
        title="Report not found"
        description="The report may not have been generated yet."
        action={
          <Button size="sm" variant="outline" onClick={() => navigate('/app/reports')}>
            Back to reports
          </Button>
        }
      />
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2 no-print">
        <Button size="sm" variant="ghost" icon={<ArrowLeft size={13} />} onClick={() => navigate('/app/reports')}>
          All reports
        </Button>
        <Button size="sm" variant="ghost" onClick={() => navigate(`/app/inspections/${inspection.id}`)}>
          Open inspection {inspection.id}
        </Button>
        <div className="ml-auto flex items-center gap-2">
          <Button
            size="sm"
            variant="outline"
            icon={<FileJson size={13} />}
            onClick={() => {
              downloadReportJson(inspection, report.id);
              toast.success('Structured export downloaded', 'JSON payload for departmental systems.');
            }}
          >
            <span className="hidden sm:inline">Structured export</span>
          </Button>
          <Button
            size="sm"
            variant="outline"
            icon={<Share2 size={13} />}
            onClick={() => {
              setReportStatus(report.id, 'SHARED');
              toast.success('Report shared', 'Shared with the supervisory officer for review.');
            }}
          >
            <span className="hidden sm:inline">Share</span>
          </Button>
        </div>
      </div>

      {/* Report preview — mirrors the exported document */}
      <article className="mx-auto w-full max-w-4xl bg-white p-6 shadow-card ring-1 ring-slate-200 sm:p-10 print-full">
        <header className="border-b-[3px] border-double border-navy-900 pb-4 text-center">
          <p className="text-2xs font-semibold uppercase tracking-[0.18em] text-slate-500">{user?.department}</p>
          <h1 className="mt-2 text-lg font-extrabold uppercase tracking-wide text-navy-900 sm:text-xl">
            Legal Metrology Compliance Inspection Report
          </h1>
          <p className="mt-1 text-xs text-slate-500">
            Legal Metrology (Packaged Commodities) Rules, 2011 — AI-assisted screening record
          </p>
          <p className="mt-2 font-mono text-2xs text-slate-400">
            {report.id} · Generated {formatDateTime(report.generatedAt)}
          </p>
        </header>

        <Section title="1 · Inspection particulars">
          <KeyValue
            rows={[
              ['Inspection ID', inspection.id],
              ['Date & time', formatDateTime(inspection.inspectedAt)],
              ['Inspecting officer', `${inspection.inspectorName}${user ? ` (${user.officialId})` : ''}`],
              ['Designation', user?.designation ?? '—'],
              ['Region / jurisdiction', inspection.region],
              ['Place of inspection', inspection.location],
              ['Source of sample', inspection.source.replace(/_/g, ' ').toLowerCase()],
            ]}
          />
        </Section>

        <Section title="2 · Product & manufacturer particulars">
          <div className="grid gap-4 sm:grid-cols-[140px_1fr]">
            <img
              src={resolveImage(inspection.ocr?.imageId)}
              alt="Scanned package"
              className="w-full rounded border border-slate-300 object-contain"
            />
            <KeyValue
              rows={[
                ['Commodity', inspection.productName],
                ['Brand', inspection.brand],
                ['Category', inspection.category],
                [
                  'Manufacturer / packer',
                  inspection.declarations.find((d) => d.key === 'MANUFACTURER_NAME')?.detectedValue ?? 'Not declared',
                ],
                [
                  'Address',
                  inspection.declarations.find((d) => d.key === 'MANUFACTURER_ADDRESS')?.detectedValue ?? 'Not declared',
                ],
                [
                  'Importer',
                  inspection.declarations.find((d) => d.key === 'IMPORTER_DETAILS')?.detectedValue ?? 'Not applicable',
                ],
                [
                  'Country of origin',
                  inspection.declarations.find((d) => d.key === 'COUNTRY_OF_ORIGIN')?.detectedValue ?? 'Not declared',
                ],
              ]}
            />
          </div>
        </Section>

        <Section title="3 · Declarations extracted from the label">
          <table className="w-full border-collapse text-xs">
            <thead>
              <tr className="bg-slate-100 text-2xs uppercase tracking-wider text-slate-600">
                <th className="border border-slate-300 px-2 py-1.5 text-left">Declaration</th>
                <th className="border border-slate-300 px-2 py-1.5 text-left">Value read from package</th>
                <th className="border border-slate-300 px-2 py-1.5 text-right">OCR confidence</th>
              </tr>
            </thead>
            <tbody>
              {inspection.declarations.map((d) => (
                <tr key={d.key}>
                  <td className="border border-slate-300 px-2 py-1.5 text-slate-700">{d.label}</td>
                  <td
                    className={cn(
                      'border border-slate-300 px-2 py-1.5',
                      d.detectedValue ? 'text-slate-900' : 'italic text-slate-400',
                    )}
                  >
                    {d.detectedValue ?? 'Not detected'}
                  </td>
                  <td className="border border-slate-300 px-2 py-1.5 text-right font-mono text-slate-600">
                    {(d.confidence * 100).toFixed(0)}%
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Section>

        <Section title="4 · Rule validation">
          <table className="w-full border-collapse text-xs">
            <thead>
              <tr className="bg-slate-100 text-2xs uppercase tracking-wider text-slate-600">
                <th className="border border-slate-300 px-2 py-1.5 text-left">Rule</th>
                <th className="border border-slate-300 px-2 py-1.5 text-left">Detected</th>
                <th className="border border-slate-300 px-2 py-1.5 text-left">Result</th>
              </tr>
            </thead>
            <tbody>
              {inspection.ruleResults.map((r) => (
                <tr key={r.ruleId}>
                  <td className="border border-slate-300 px-2 py-1.5">
                    <p className="font-medium text-slate-800">{r.ruleName}</p>
                    <p className="font-mono text-[10px] text-slate-400">
                      {r.ruleId} · {r.legalReference}
                    </p>
                  </td>
                  <td className="border border-slate-300 px-2 py-1.5 text-slate-700">{r.detectedValue ?? '—'}</td>
                  <td
                    className={cn(
                      'border border-slate-300 px-2 py-1.5 font-semibold',
                      r.status === 'PASS'
                        ? 'text-emerald-700'
                        : r.status === 'FAIL'
                          ? 'text-red-700'
                          : r.status === 'REVIEW'
                            ? 'text-amber-700'
                            : 'text-slate-500',
                    )}
                  >
                    {RULE_STATUS_LABEL[r.status]}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Section>

        <Section title="5 · Findings">
          {inspection.violations.length === 0 ? (
            <p className="text-xs text-slate-600">
              No findings were raised by the screening engine for this package.
            </p>
          ) : (
            <div className="space-y-3">
              {inspection.violations.map((v, i) => (
                <div key={v.id} className="border-l-4 border-red-700 bg-red-50/60 px-3 py-2.5">
                  <div className="flex flex-wrap items-center gap-2">
                    <h3 className="text-xs font-bold text-slate-900">
                      Finding {i + 1}: {v.title}
                    </h3>
                    <SeverityBadge severity={v.severity} />
                  </div>
                  <dl className="mt-1.5 space-y-1 text-2xs text-slate-700">
                    <div className="flex gap-2">
                      <dt className="w-24 shrink-0 font-semibold text-slate-500">Detected</dt>
                      <dd>{v.detected}</dd>
                    </div>
                    <div className="flex gap-2">
                      <dt className="w-24 shrink-0 font-semibold text-slate-500">Basis</dt>
                      <dd>{v.explanation}</dd>
                    </div>
                    <div className="flex gap-2">
                      <dt className="w-24 shrink-0 font-semibold text-slate-500">Verification</dt>
                      <dd>{v.recommendedAction}</dd>
                    </div>
                    <div className="flex gap-2">
                      <dt className="w-24 shrink-0 font-semibold text-slate-500">Reference</dt>
                      <dd>{v.legalReference}</dd>
                    </div>
                    {v.officerNote && (
                      <div className="flex gap-2">
                        <dt className="w-24 shrink-0 font-semibold text-slate-500">Officer note</dt>
                        <dd>{v.officerNote}</dd>
                      </div>
                    )}
                  </dl>
                </div>
              ))}
            </div>
          )}
        </Section>

        <Section title="6 · AI screening result">
          <div className="flex flex-wrap items-center gap-6 border border-slate-300 bg-slate-50 p-4">
            <div>
              <p className="font-mono text-3xl font-extrabold text-navy-900">
                {inspection.screeningScore}
                <span className="text-base text-slate-400"> / 100</span>
              </p>
              <p className="mt-1 text-2xs uppercase tracking-wider text-slate-500">AI screening score</p>
            </div>
            <div className="grid flex-1 gap-1 text-2xs sm:grid-cols-2">
              {[
                ['Mandatory declarations', inspection.scoreBreakdown.mandatoryDeclarations],
                ['Formatting', inspection.scoreBreakdown.formatting],
                ['Readability', inspection.scoreBreakdown.readability],
                ['Packaging information', inspection.scoreBreakdown.packagingInformation],
              ].map(([label, v]) => {
                const val = v as { score: number; max: number };
                return (
                  <div key={String(label)} className="flex justify-between gap-3 text-slate-600">
                    <span>{String(label)}</span>
                    <span className="font-mono font-semibold text-slate-800">
                      {val.score}/{val.max}
                    </span>
                  </div>
                );
              })}
            </div>
            <div className="text-right">
              <p className="text-2xs uppercase tracking-wider text-slate-500">Final screening status</p>
              <p className="mt-1">
                <StatusBadge status={inspection.status} />
              </p>
              <p className="mt-1 text-2xs text-slate-500">{STATUS_LABEL[inspection.status]}</p>
            </div>
          </div>
        </Section>

        <Section title="7 · Inspector remarks">
          <p className="min-h-[3rem] whitespace-pre-wrap border border-slate-300 bg-white px-3 py-2 text-xs leading-relaxed text-slate-700">
            {inspection.remarks || 'No remarks recorded.'}
          </p>
        </Section>

        <Section title="8 · Evidence & audit trail">
          <div className="mb-3 grid grid-cols-3 gap-2 sm:grid-cols-5">
            {evidence.slice(0, 5).map((e) => (
              <figure key={e.id}>
                <img
                  src={e.dataUrl ?? resolveImage(e.imageId)}
                  alt={e.description}
                  className="aspect-[3/4] w-full rounded border border-slate-300 object-cover object-top"
                />
                <figcaption className="mt-1 truncate font-mono text-[10px] text-slate-400">
                  {e.evidenceNumber}
                </figcaption>
              </figure>
            ))}
          </div>
          <table className="w-full border-collapse text-2xs">
            <thead>
              <tr className="bg-slate-100 uppercase tracking-wider text-slate-600">
                <th className="border border-slate-300 px-2 py-1 text-left">Timestamp</th>
                <th className="border border-slate-300 px-2 py-1 text-left">Actor</th>
                <th className="border border-slate-300 px-2 py-1 text-left">Action</th>
              </tr>
            </thead>
            <tbody>
              {inspection.auditLog.map((a) => (
                <tr key={a.id}>
                  <td className="border border-slate-300 px-2 py-1 font-mono text-slate-500">
                    {formatDateTime(a.at)}
                  </td>
                  <td className="border border-slate-300 px-2 py-1 text-slate-700">{a.actor}</td>
                  <td className="border border-slate-300 px-2 py-1 text-slate-700">
                    {a.action}
                    {a.detail ? ` — ${a.detail}` : ''}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Section>

        <p className="mt-6 border border-slate-400 bg-slate-50 px-3 py-2.5 text-2xs italic leading-relaxed text-slate-700">
          {REPORT_DISCLAIMER}
        </p>

        <div className="mt-10 flex flex-wrap items-end justify-between gap-6 text-2xs text-slate-500">
          <span>Generated by LM-Inspect AI on {formatDateTime(report.generatedAt)}</span>
          <span className="text-right">
            <span className="block border-t border-slate-400 pt-1">{inspection.inspectorName}</span>
            <span className="block">{user?.designation}</span>
          </span>
        </div>
      </article>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-7">
      <h2 className="mb-2 border-b-2 border-navy-900 pb-1 text-2xs font-bold uppercase tracking-wider text-navy-900">
        {title}
      </h2>
      {children}
    </section>
  );
}

function KeyValue({ rows }: { rows: [string, string][] }) {
  return (
    <dl className="grid gap-1.5 text-xs sm:grid-cols-2">
      {rows.map(([k, v]) => (
        <div key={k} className="flex gap-2">
          <dt className="w-32 shrink-0 text-slate-500">{k}</dt>
          <dd className="min-w-0 flex-1 font-medium capitalize text-slate-800">{v}</dd>
        </div>
      ))}
    </dl>
  );
}
